create – Shu-Osher-shock-tube-problem
create Subroutine
Source File
Subroutines
set_weights_optimal set_polynomial_coefficients set_smoothness_indicators_coefficients
Source Code
create
All Procedures
a add add_3d_plot add_bar add_cla_clasg add_euler add_group add_plot add_str assign_cla assign_clasg assign_cli assign_interpolator assign_object called_group check check_choices_cla check_cla check_clasg check_list_size_cla check_m_exclusive check_m_exclusive_clasg check_required_clasg command_line_interface compute_dt compute_inter_states conservative2primitive create create defined defined_clasg defined_group description destroy destroy destroy destroy destroy destroy destroy destroy destroy dEuler_dt E errored euler_assign_euler euler_assign_real euler_local_error euler_multiply_euler euler_multiply_real execute finalize finalize finalize finalize finalize finalize finalize finalize finalize finalize_cla finalize_clasg finish free free_cla free_clasg free_object get_args_from_invocation get_args_from_string get_cla get_cla_cli get_cla_list get_cla_list_cli get_cla_list_varying_char get_cla_list_varying_char_cli get_cla_list_varying_I1P get_cla_list_varying_I1P_cli get_cla_list_varying_I2P get_cla_list_varying_I2P_cli get_cla_list_varying_I4P get_cla_list_varying_I4P_cli get_cla_list_varying_I8P get_cla_list_varying_I8P_cli get_cla_list_varying_logical get_cla_list_varying_logical_cli get_cla_list_varying_R16P get_cla_list_varying_R16P_cli get_cla_list_varying_R4P get_cla_list_varying_R4P_cli get_cla_list_varying_R8P get_cla_list_varying_R8P_cli get_clasg_indexes H impose_boundary_conditions init init init init init init init init init init initialize integer_to_string integrate integrate integrate integrate integrate integrate integrate integrate interpolate new_Dt optional_int_to_string output p parse parse_clasg passed passed_clasg primitive2conservative print_usage print_version r real_multiply_euler reconstruct_interfaces_states riemann_solver save_man_page save_results save_time_serie savefig set_mutually_exclusive_groups signature signature_cla signature_clasg sub_euler tokenize update_previous update_previous Upper_Case usage usage_cla usage_clasg vec_to_string weno_constructor_upwind weno_constructor_upwind_init
private subroutine create(self, constructor)
Arguments
Type Intent Optional Attributes Name
class(weno_interpolator_upwind), intent(inout) :: self
WENO interpolator.
class(weno_constructor), intent(in) :: constructor
WENO constructor.
Description
Create the WENO interpolator.
Calls
Subroutines
subroutine set_weights_optimal()
Arguments
None
Description
Set the values of optimial weights.
subroutine set_polynomial_coefficients()
Arguments
None
Description
Set the values of polynomial_coefficient.
subroutine set_smoothness_indicators_coefficients()
Arguments
None
Description
Set the values of smoothness indicators coefficients.
Source Code
  subroutine create(self, constructor)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Create the WENO interpolator.
  !---------------------------------------------------------------------------------------------------------------------------------
  class(weno_interpolator_upwind), intent(INOUT) :: self        !< WENO interpolator.
  class(weno_constructor),         intent(IN)    :: constructor !< WENO constructor.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  select type(constructor)
  type is(weno_constructor_upwind)
    call self%destroy
    self%S = constructor%S
    self%eps = constructor%eps
    allocate(self%weights_opt(1:2, 0:self%S - 1))
    allocate(self%poly_coef(1:2, 0:self%S - 1, 0:self%S - 1))
    allocate(self%smooth_coef(0:self%S - 1, 0:self%S - 1, 0:self%S - 1))
    call set_weights_optimal
    call set_polynomial_coefficients
    call set_smoothness_indicators_coefficients
  endselect
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  contains
    subroutine set_weights_optimal()
    !-------------------------------------------------------------------------------------------------------------------------------
    !< Set the values of optimial weights.
    !-------------------------------------------------------------------------------------------------------------------------------
    !-------------------------------------------------------------------------------------------------------------------------------
    select case(self%S)
    case(2) ! 3rd order
      ! 1 => left interface (i-1/2)
      self%weights_opt(1, 0) = 2._R_P/3._R_P ! stencil 0
      self%weights_opt(1, 1) = 1._R_P/3._R_P ! stencil 1
      ! 2 => right interface (i+1/2)
      self%weights_opt(2, 0) = 1._R_P/3._R_P ! stencil 0
      self%weights_opt(2, 1) = 2._R_P/3._R_P ! stencil 1
    case(3) ! 5th order
      ! 1 => left interface (i-1/2)
      self%weights_opt(1, 0) = 0.3_R_P ! stencil 0
      self%weights_opt(1, 1) = 0.6_R_P ! stencil 1
      self%weights_opt(1, 2) = 0.1_R_P ! stencil 2
      ! 2 => right interface (i+1/2)
      self%weights_opt(2, 0) = 0.1_R_P ! stencil 0
      self%weights_opt(2, 1) = 0.6_R_P ! stencil 1
      self%weights_opt(2, 2) = 0.3_R_P ! stencil 2
    case(4) ! 7th order
      ! 1 => left interface (i-1/2)
      self%weights_opt(1, 0) =  4._R_P/35._R_P ! stencil 0
      self%weights_opt(1, 1) = 18._R_P/35._R_P ! stencil 1
      self%weights_opt(1, 2) = 12._R_P/35._R_P ! stencil 2
      self%weights_opt(1, 3) =  1._R_P/35._R_P ! stencil 3
      ! 2 => right interface (i+1/2)
      self%weights_opt(2, 0) =  1._R_P/35._R_P ! stencil 0
      self%weights_opt(2, 1) = 12._R_P/35._R_P ! stencil 1
      self%weights_opt(2, 2) = 18._R_P/35._R_P ! stencil 2
      self%weights_opt(2, 3) =  4._R_P/35._R_P ! stencil 3
    endselect
    return
    !-------------------------------------------------------------------------------------------------------------------------------
    endsubroutine set_weights_optimal
    subroutine set_polynomial_coefficients()
    !-------------------------------------------------------------------------------------------------------------------------------
    !< Set the values of polynomial_coefficient.
    !-------------------------------------------------------------------------------------------------------------------------------
    !-------------------------------------------------------------------------------------------------------------------------------
    associate(coef => self%poly_coef)
      select case(self%S)
      case(2) ! 3rd order
        ! 1 => left interface (i-1/2)
        !  cell  0               ;    cell  1
        coef(1, 0, 0) =  0.5_R_P ; coef(1, 1, 0) =  0.5_R_P ! stencil 0
        coef(1, 0, 1) = -0.5_R_P ; coef(1, 1, 1) =  1.5_R_P ! stencil 1
        ! 2 => right interface (i+1/2)
        !  cell  0               ;    cell  1
        coef(2, 0, 0) =  1.5_R_P ; coef(2, 1, 0) = -0.5_R_P ! stencil 0
        coef(2, 0, 1) =  0.5_R_P ; coef(2, 1, 1) =  0.5_R_P ! stencil 1
      case(3) ! 5th order
        ! 1 => left interface (i-1/2)
        !  cell  0                     ;    cell  1                     ;    cell  2
        coef(1, 0, 0) =  1._R_P/3._R_P ; coef(1, 1, 0) =  5._R_P/6._R_P ; coef(1, 2, 0) = -1._R_P/6._R_P ! stencil 0
        coef(1, 0, 1) = -1._R_P/6._R_P ; coef(1, 1, 1) =  5._R_P/6._R_P ; coef(1, 2, 1) =  1._R_P/3._R_P ! stencil 1
        coef(1, 0, 2) =  1._R_P/3._R_P ; coef(1, 1, 2) = -7._R_P/6._R_P ; coef(1, 2, 2) = 11._R_P/6._R_P ! stencil 2
        ! 2 => right interface (i+1/2)
        !  cell  0                     ;    cell  1                     ;    cell  2
        coef(2, 0, 0) = 11._R_P/6._R_P ; coef(2, 1, 0) = -7._R_P/6._R_P ; coef(2, 2, 0) =  1._R_P/3._R_P ! stencil 0
        coef(2, 0, 1) =  1._R_P/3._R_P ; coef(2, 1, 1) =  5._R_P/6._R_P ; coef(2, 2, 1) = -1._R_P/6._R_P ! stencil 1
        coef(2, 0, 2) = -1._R_P/6._R_P ; coef(2, 1, 2) =  5._R_P/6._R_P ; coef(2, 2, 2) =  1._R_P/3._R_P ! stencil 2
      case(4) ! 7th order
        ! 1 => left interface (i-1/2)
        !  cell  0                 ;   cell  1                 ;   cell  2                  ;   cell  3
        coef(1,0,0)= 1._R_P/4._R_P ;coef(1,1,0)=13._R_P/12._R_P;coef(1,2,0)= -5._R_P/12._R_P;coef(1,3,0)= 1._R_P/12._R_P ! sten 0
        coef(1,0,1)=-1._R_P/12._R_P;coef(1,1,1)= 7._R_P/12._R_P;coef(1,2,1)=  7._R_P/12._R_P;coef(1,3,1)=-1._R_P/12._R_P ! sten 1
        coef(1,0,2)= 1._R_P/12._R_P;coef(1,1,2)=-5._R_P/12._R_P;coef(1,2,2)= 13._R_P/12._R_P;coef(1,3,2)= 1._R_P/4._R_P  ! sten 2
        coef(1,0,3)=-1._R_P/4._R_P ;coef(1,1,3)=13._R_P/12._R_P;coef(1,2,3)=-23._R_P/12._R_P;coef(1,3,3)=25._R_P/12._R_P ! sten 3
        ! 2 => right interface (i+1/2)
        !  cell  0                 ;   cell  1                  ;   cell  2                 ;   cell  3
        coef(2,0,0)=25._R_P/12._R_P;coef(2,1,0)=-23._R_P/12._R_P;coef(2,2,0)=13._R_P/12._R_P;coef(2,3,0)=-1._R_P/4._R_P  ! sten 0
        coef(2,0,1)= 1._R_P/4._R_P ;coef(2,1,1)= 13._R_P/12._R_P;coef(2,2,1)=-5._R_P/12._R_P;coef(2,3,1)= 1._R_P/12._R_P ! sten 1
        coef(2,0,2)=-1._R_P/12._R_P;coef(2,1,2)=  7._R_P/12._R_P;coef(2,2,2)= 7._R_P/12._R_P;coef(2,3,2)=-1._R_P/12._R_P ! sten 2
        coef(2,0,3)= 1._R_P/12._R_P;coef(2,1,3)= -5._R_P/12._R_P;coef(2,2,3)=13._R_P/12._R_P;coef(2,3,3)= 1._R_P/4._R_P  ! sten 3
      endselect
    endassociate
    return
    !-------------------------------------------------------------------------------------------------------------------------------
    endsubroutine set_polynomial_coefficients
    subroutine set_smoothness_indicators_coefficients()
    !-------------------------------------------------------------------------------------------------------------------------------
    !< Set the values of smoothness indicators coefficients.
    !-------------------------------------------------------------------------------------------------------------------------------
    !-------------------------------------------------------------------------------------------------------------------------------
    associate(coef => self%smooth_coef)
      select case(self%S)
      case(2) ! 3rd order
        ! stencil 0
        !      i*i             ;       (i-1)*i
        coef(0, 0, 0) = 1._R_P ; coef(1, 0, 0) = -2._R_P
        !      /               ;       (i-1)*(i-1)
        coef(0, 1, 0) = 0._R_P ; coef(1, 1, 0) = 1._R_P
        ! stencil 1
        !     (i+1)*(i+1)      ;       (i+1)*i
        coef(0, 0, 1) = 1._R_P ; coef(1, 0, 1) = -2._R_P
        !      /               ;        i*i
        coef(0, 1, 1) = 0._R_P ; coef(1, 1, 1) = 1._R_P
      case(3) ! 5th order
        ! stencil 0
        !      i*i                      ;       (i-1)*i                   ;       (i-2)*i
        coef(0, 0, 0) =  10._R_P/3._R_P ; coef(1, 0, 0) = -31._R_P/3._R_P ; coef(2, 0, 0) =  11._R_P/3._R_P
        !      /                        ;       (i-1)*(i-1)               ;       (i-2)*(i-1)
        coef(0, 1, 0) =   0._R_P        ; coef(1, 1, 0) =  25._R_P/3._R_P ; coef(2, 1, 0) = -19._R_P/3._R_P
        !      /                        ;        /                        ;       (i-2)*(i-2)
        coef(0, 2, 0) =   0._R_P        ; coef(1, 2, 0) =   0._R_P        ; coef(2, 2, 0) =   4._R_P/3._R_P
        ! stencil 1
        !     (i+1)*(i+1)               ;        i*(i+1)                  ;       (i-1)*(i+1)
        coef(0, 0, 1) =   4._R_P/3._R_P ; coef(1, 0, 1) = -13._R_P/3._R_P ; coef(2, 0, 1) =   5._R_P/3._R_P
        !      /                        ;        i*i                      ;       (i-1)*i
        coef(0, 1, 1) =   0._R_P        ; coef(1, 1, 1) =  13._R_P/3._R_P ; coef(2, 1, 1) = -13._R_P/3._R_P
        !      /                        ;        /                        ;       (i-1)*(i-1)
        coef(0, 2, 1) =   0._R_P        ; coef(1, 2, 1) =   0._R_P        ; coef(2, 2, 1) =   4._R_P/3._R_P
        ! stencil 2
        !     (i+2)*(i+2)               ;       (i+1)*(i+2)               ;        i*(i+2)
        coef(0, 0, 2) =   4._R_P/3._R_P ; coef(1, 0, 2) = -19._R_P/3._R_P ; coef(2, 0, 2) =  11._R_P/3._R_P
        !      /                        ;       (i+1)*(i+1)               ;        i*(i+1)
        coef(0, 1, 2) =   0._R_P        ; coef(1, 1, 2) =  25._R_P/3._R_P ; coef(2, 1, 2) = -31._R_P/3._R_P
        !      /                        ;        /                        ;        i*i
        coef(0, 2, 2) =   0._R_P        ; coef(1, 2, 2) =   0._R_P        ; coef(2, 2, 2) =  10._R_P/3._R_P
      case(4) ! 7th order
        ! stencil 0
        !      i*i                ;       (i-1)*i             ;       (i-2)*i              ;       (i-3)*i
        coef(0, 0, 0) = 2107._R_P ; coef(1, 0, 0) =-9402._R_P ; coef(2, 0, 0) =  7042._R_P ; coef(3, 0, 0) = -1854._R_P
        !      /                  ;       (i-1)*(i-1)         ;       (i-2)*(i-1)          ;       (i-3)*(i-1)
        coef(0, 1, 0) =    0._R_P ; coef(1, 1, 0) =11003._R_P ; coef(2, 1, 0) =-17246._R_P ; coef(3, 1, 0) =  4642._R_P
        !      /                  ;        /                  ;       (i-2)*(i-2)          ;       (i-3)*(i-2)
        coef(0, 2, 0) =    0._R_P ; coef(1, 2, 0) =    0._R_P ; coef(2, 2, 0) =  7043._R_P ; coef(3, 2, 0) = -3882._R_P
        !      /                  ;        /                  ;        /                   ;       (i-3)*(i-3)
        coef(0, 3, 0) =    0._R_P ; coef(1, 3, 0) =    0._R_P ; coef(2, 3, 0) =     0._R_P ; coef(3, 3, 0) =   547._R_P
        ! stencil 1
        !     (i+1)*(i+1)         ;        i*(i+1)            ;       (i-1)*(i+1)          ;       (i-2)*(i+1)
        coef(0, 0, 1) =  547._R_P ; coef(1, 0, 1) =-2522._R_P ; coef(2, 0, 1) =  1922._R_P ; coef(3, 0, 1) =  -494._R_P
        !       /                 ;          i*i              ;       (i-1)*i              ;       (i-2)*i
        coef(0, 1, 1) =    0._R_P ; coef(1, 1, 1) = 3443._R_P ; coef(2, 1, 1) = -5966._R_P ; coef(3, 1, 1) =  1602._R_P
        !       /                 ;          /                ;       (i-1)*(i-1)          ;       (i-2)*(i-1)
        coef(0, 2, 1) =    0._R_P ; coef(1, 2, 1) =    0._R_P ; coef(2, 2, 1) =  2843._R_P ; coef(3, 2, 1) = -1642._R_P
        !       /                 ;          /                ;        /                   ;       (i-2)*(i-2)
        coef(0, 3, 1) =    0._R_P ; coef(1, 3, 1) =    0._R_P ; coef(2, 3, 1) =     0._R_P ; coef(3, 3, 1) =   267._R_P
        ! stencil 2
        !     (i+2)*(i+2)         ;       (i+1)*(i+2)         ;            i*(i+2)         ;       (i-1)*(i+2)
        coef(0, 0, 2) =  267._R_P ; coef(1, 0, 2) =-1642._R_P ; coef(2, 0, 2) =  1602._R_P ; coef(3, 0, 2) =  -494._R_P
        !      /                  ;       (i+1)*(i+1)         ;        i*(i+1)             ;       (i-1)*(i+1)
        coef(0, 1, 2) =    0._R_P ; coef(1, 1, 2) = 2843._R_P ; coef(2, 1, 2) = -5966._R_P ; coef(3, 1, 2) =  1922._R_P
        !      /                  ;        /                  ;        i*i                 ;       (i-1)*i
        coef(0, 2, 2) =    0._R_P ; coef(1, 2, 2) =    0._R_P ; coef(2, 2, 2) =  3443._R_P ; coef(3, 2, 2) = -2522._R_P
        !      /                  ;        /                  ;        /                   ;       (i-1)*(i-1)
        coef(0, 3, 2) =    0._R_P ; coef(1, 3, 2) =    0._R_P ; coef(2, 3, 2) =     0._R_P ; coef(3, 3, 2) =   547._R_P
        ! stencil 3
        !     (i+3)*(i+3)         ;       (i+2)*(i+3)         ;           (i+1)*(i+3)      ;        i*(i+3)
        coef(0, 0, 3) =  547._R_P ; coef(1, 0, 3) =-3882._R_P ; coef(2, 0, 3) =  4642._R_P ; coef(3, 0, 3) = -1854._R_P
        !      /                  ;       (i+2)*(i+2)         ;       (i+1)*(i+2)          ;        i*(i+2)
        coef(0, 1, 3) =    0._R_P ; coef(1, 1, 3) = 7043._R_P ; coef(2, 1, 3) =-17246._R_P ; coef(3, 1, 3) =  7042._R_P
        !      /                  ;        /                  ;       (i+1)*(i+1)          ;        i*(i+1)
        coef(0, 2, 3) =    0._R_P ; coef(1, 2, 3) =    0._R_P ; coef(2, 2, 3) = 11003._R_P ; coef(3, 2, 3) = -9402._R_P
        !      /                  ;        /                  ;        /                   ;        i*i
        coef(0, 3, 3) =    0._R_P ; coef(1, 3, 3) =    0._R_P ; coef(2, 3, 3) =     0._R_P ; coef(3, 3, 3) =  2107._R_P
      endselect
    endassociate
    return
    !-------------------------------------------------------------------------------------------------------------------------------
    endsubroutine set_smoothness_indicators_coefficients
  endsubroutine create
Call graph
create calls set_polynomial_coefficients, set_weights_optimal, set_smoothness_indicators_coefficients